version: "3.1"

services:
  database:
    image: mongo:4.2.23-bionic
    restart: unless-stopped
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: tasks_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
