version: "3.1"

services:
  database:
    image: mongo:4.2.23-bionic
    restart: unless-stopped
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: tasks_db
    volumes:
      - ce-db:/data/db
  api:
    image: ce-api
    build: .
    ports:
      - "3001:3001"
volumes:
  ce-db:
